package com.facebook.react.bridge;

import kotlin.Metadata;
import kotlin.enums.EnumEntries;
import kotlin.jvm.internal.DefaultConstructorMarker;
import org.jetbrains.annotations.NotNull;

/* JADX INFO: loaded from: classes2.dex */
@Metadata(d1 = {"\u0000\u0012\n\u0002\u0018\u0002\n\u0002\u0010\u0010\n\u0000\n\u0002\u0010\u000b\n\u0002\bv\b\u0086\u0081\u0002\u0018\u00002\b\u0012\u0004\u0012\u00020\u00000\u0001B\u0013\b\u0002\u0012\b\b\u0002\u0010\u0002\u001a\u00020\u0003¢\u0006\u0004\b\u0004\u0010\u0005R\u0013\u0010\u0002\u001a\u00020\u00038G¢\u0006\b\n\u0000\u001a\u0004\b\u0002\u0010\u0006j\u0002\b\u0007j\u0002\b\bj\u0002\b\tj\u0002\b\nj\u0002\b\u000bj\u0002\b\fj\u0002\b\rj\u0002\b\u000ej\u0002\b\u000fj\u0002\b\u0010j\u0002\b\u0011j\u0002\b\u0012j\u0002\b\u0013j\u0002\b\u0014j\u0002\b\u0015j\u0002\b\u0016j\u0002\b\u0017j\u0002\b\u0018j\u0002\b\u0019j\u0002\b\u001aj\u0002\b\u001bj\u0002\b\u001cj\u0002\b\u001dj\u0002\b\u001ej\u0002\b\u001fj\u0002\b j\u0002\b!j\u0002\b\"j\u0002\b#j\u0002\b$j\u0002\b%j\u0002\b&j\u0002\b'j\u0002\b(j\u0002\b)j\u0002\b*j\u0002\b+j\u0002\b,j\u0002\b-j\u0002\b.j\u0002\b/j\u0002\b0j\u0002\b1j\u0002\b2j\u0002\b3j\u0002\b4j\u0002\b5j\u0002\b6j\u0002\b7j\u0002\b8j\u0002\b9j\u0002\b:j\u0002\b;j\u0002\b<j\u0002\b=j\u0002\b>j\u0002\b?j\u0002\b@j\u0002\bAj\u0002\bBj\u0002\bCj\u0002\bDj\u0002\bEj\u0002\bFj\u0002\bGj\u0002\bHj\u0002\bIj\u0002\bJj\u0002\bKj\u0002\bLj\u0002\bMj\u0002\bNj\u0002\bOj\u0002\bPj\u0002\bQj\u0002\bRj\u0002\bSj\u0002\bTj\u0002\bUj\u0002\bVj\u0002\bWj\u0002\bXj\u0002\bYj\u0002\bZj\u0002\b[j\u0002\b\\j\u0002\b]j\u0002\b^j\u0002\b_j\u0002\b`j\u0002\baj\u0002\bbj\u0002\bcj\u0002\bdj\u0002\bej\u0002\bfj\u0002\bgj\u0002\bhj\u0002\bij\u0002\bjj\u0002\bkj\u0002\blj\u0002\bmj\u0002\bnj\u0002\boj\u0002\bpj\u0002\bqj\u0002\brj\u0002\bsj\u0002\btj\u0002\buj\u0002\bvj\u0002\bwj\u0002\bx¨\u0006y"}, d2 = {"Lcom/facebook/react/bridge/ReactMarkerConstants;", "", "hasMatchingNameMarker", "", "<init>", "(Ljava/lang/String;IZ)V", "()Z", "APP_STARTUP_START", "APP_STARTUP_END", "CREATE_REACT_CONTEXT_START", "CREATE_REACT_CONTEXT_END", "INIT_REACT_RUNTIME_START", "INIT_REACT_RUNTIME_END", "PROCESS_PACKAGES_START", "PROCESS_PACKAGES_END", "BUILD_NATIVE_MODULE_REGISTRY_START", "BUILD_NATIVE_MODULE_REGISTRY_END", "CREATE_CATALYST_INSTANCE_START", "CREATE_CATALYST_INSTANCE_END", "DESTROY_CATALYST_INSTANCE_START", "DESTROY_CATALYST_INSTANCE_END", "RUN_JS_BUNDLE_START", "RUN_JS_BUNDLE_END", "NATIVE_MODULE_INITIALIZE_START", "NATIVE_MODULE_INITIALIZE_END", "SETUP_REACT_CONTEXT_START", "SETUP_REACT_CONTEXT_END", "CHANGE_THREAD_PRIORITY", "CREATE_UI_MANAGER_MODULE_START", "CREATE_UI_MANAGER_MODULE_END", "CREATE_VIEW_MANAGERS_START", "CREATE_VIEW_MANAGERS_END", "CREATE_UI_MANAGER_MODULE_CONSTANTS_START", "CREATE_UI_MANAGER_MODULE_CONSTANTS_END", "NATIVE_MODULE_SETUP_START", "NATIVE_MODULE_SETUP_END", "CREATE_MODULE_START", "CREATE_MODULE_END", "PROCESS_CORE_REACT_PACKAGE_START", "PROCESS_CORE_REACT_PACKAGE_END", "CREATE_I18N_MODULE_CONSTANTS_START", "CREATE_I18N_MODULE_CONSTANTS_END", "I18N_MODULE_CONSTANTS_CONVERT_START", "I18N_MODULE_CONSTANTS_CONVERT_END", "GET_CONSTANTS_START", "GET_CONSTANTS_END", "INITIALIZE_MODULE_START", "INITIALIZE_MODULE_END", "ON_HOST_RESUME_START", "ON_HOST_RESUME_END", "ON_USER_LEAVE_HINT_START", "ON_USER_LEAVE_HINT_END", "ON_HOST_PAUSE_START", "ON_HOST_PAUSE_END", "CONVERT_CONSTANTS_START", "CONVERT_CONSTANTS_END", "PRE_REACT_CONTEXT_END", "UNPACKING_JS_BUNDLE_LOADER_CHECK_START", "UNPACKING_JS_BUNDLE_LOADER_CHECK_END", "UNPACKING_JS_BUNDLE_LOADER_EXTRACTED", "UNPACKING_JS_BUNDLE_LOADER_BLOCKED", "loadApplicationScript_startStringConvert", "loadApplicationScript_endStringConvert", "PRE_SETUP_REACT_CONTEXT_START", "PRE_SETUP_REACT_CONTEXT_END", "PRE_RUN_JS_BUNDLE_START", "ATTACH_MEASURED_ROOT_VIEWS_START", "ATTACH_MEASURED_ROOT_VIEWS_END", "CONTENT_APPEARED", "RELOAD", "DOWNLOAD_START", "DOWNLOAD_END", "REACT_CONTEXT_THREAD_START", "REACT_CONTEXT_THREAD_END", "GET_REACT_INSTANCE_MANAGER_START", "GET_REACT_INSTANCE_MANAGER_END", "GET_REACT_INSTANCE_HOLDER_SPEC_START", "GET_REACT_INSTANCE_HOLDER_SPEC_END", "BUILD_REACT_INSTANCE_MANAGER_START", "BUILD_REACT_INSTANCE_MANAGER_END", "PROCESS_INFRA_PACKAGE_START", "PROCESS_INFRA_PACKAGE_END", "PROCESS_PRODUCT_PACKAGE_START", "PROCESS_PRODUCT_PACKAGE_END", "CREATE_MC_MODULE_START", "CREATE_MC_MODULE_END", "CREATE_MC_MODULE_GET_METADATA_START", "CREATE_MC_MODULE_GET_METADATA_END", "REGISTER_JS_SEGMENT_START", "REGISTER_JS_SEGMENT_STOP", "VM_INIT", "ON_FRAGMENT_CREATE", "JAVASCRIPT_EXECUTOR_FACTORY_INJECT_START", "JAVASCRIPT_EXECUTOR_FACTORY_INJECT_END", "LOAD_REACT_NATIVE_SO_FILE_START", "LOAD_REACT_NATIVE_SO_FILE_END", "ROOT_VIEW_ON_MEASURE_START", "ROOT_VIEW_ON_MEASURE_END", "ROOT_VIEW_ATTACH_TO_REACT_INSTANCE_MANAGER_START", "ROOT_VIEW_ATTACH_TO_REACT_INSTANCE_MANAGER_END", "ROOT_VIEW_UPDATE_LAYOUT_SPECS_START", "ROOT_VIEW_UPDATE_LAYOUT_SPECS_END", "LOAD_REACT_NATIVE_FABRIC_SO_FILE_START", "LOAD_REACT_NATIVE_FABRIC_SO_FILE_END", "FABRIC_COMMIT_START", "FABRIC_COMMIT_END", "FABRIC_FINISH_TRANSACTION_START", "FABRIC_FINISH_TRANSACTION_END", "FABRIC_DIFF_START", "FABRIC_DIFF_END", "FABRIC_LAYOUT_START", "FABRIC_LAYOUT_END", "FABRIC_LAYOUT_AFFECTED_NODES", "FABRIC_BATCH_EXECUTION_START", "FABRIC_BATCH_EXECUTION_END", "FABRIC_UPDATE_UI_MAIN_THREAD_START", "FABRIC_UPDATE_UI_MAIN_THREAD_END", "REACT_BRIDGE_LOADING_START", "REACT_BRIDGE_LOADING_END", "REACT_BRIDGELESS_LOADING_START", "REACT_BRIDGELESS_LOADING_END", "ReactAndroid_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
public enum ReactMarkerConstants {
    APP_STARTUP_START(true),
    APP_STARTUP_END(true),
    CREATE_REACT_CONTEXT_START(false, 1, null),
    CREATE_REACT_CONTEXT_END(true),
    INIT_REACT_RUNTIME_START(true),
    INIT_REACT_RUNTIME_END(true),
    PROCESS_PACKAGES_START(false, 1, null),
    PROCESS_PACKAGES_END(false, 1, null),
    BUILD_NATIVE_MODULE_REGISTRY_START(false, 1, null),
    BUILD_NATIVE_MODULE_REGISTRY_END(false, 1, null),
    CREATE_CATALYST_INSTANCE_START(false, 1, null),
    CREATE_CATALYST_INSTANCE_END(false, 1, null),
    DESTROY_CATALYST_INSTANCE_START(false, 1, null),
    DESTROY_CATALYST_INSTANCE_END(false, 1, null),
    RUN_JS_BUNDLE_START(true),
    RUN_JS_BUNDLE_END(true),
    NATIVE_MODULE_INITIALIZE_START(false, 1, null),
    NATIVE_MODULE_INITIALIZE_END(false, 1, null),
    SETUP_REACT_CONTEXT_START(false, 1, null),
    SETUP_REACT_CONTEXT_END(false, 1, null),
    CHANGE_THREAD_PRIORITY(false, 1, null),
    CREATE_UI_MANAGER_MODULE_START(false, 1, null),
    CREATE_UI_MANAGER_MODULE_END(false, 1, null),
    CREATE_VIEW_MANAGERS_START(false, 1, null),
    CREATE_VIEW_MANAGERS_END(false, 1, null),
    CREATE_UI_MANAGER_MODULE_CONSTANTS_START(false, 1, null),
    CREATE_UI_MANAGER_MODULE_CONSTANTS_END(false, 1, null),
    NATIVE_MODULE_SETUP_START(true),
    NATIVE_MODULE_SETUP_END(true),
    CREATE_MODULE_START(false, 1, null),
    CREATE_MODULE_END(false, 1, null),
    PROCESS_CORE_REACT_PACKAGE_START(false, 1, null),
    PROCESS_CORE_REACT_PACKAGE_END(false, 1, null),
    CREATE_I18N_MODULE_CONSTANTS_START(false, 1, null),
    CREATE_I18N_MODULE_CONSTANTS_END(false, 1, null),
    I18N_MODULE_CONSTANTS_CONVERT_START(false, 1, null),
    I18N_MODULE_CONSTANTS_CONVERT_END(false, 1, null),
    GET_CONSTANTS_START(false, 1, null),
    GET_CONSTANTS_END(false, 1, null),
    INITIALIZE_MODULE_START(false, 1, null),
    INITIALIZE_MODULE_END(false, 1, null),
    ON_HOST_RESUME_START(false, 1, null),
    ON_HOST_RESUME_END(false, 1, null),
    ON_USER_LEAVE_HINT_START(false, 1, null),
    ON_USER_LEAVE_HINT_END(false, 1, null),
    ON_HOST_PAUSE_START(false, 1, null),
    ON_HOST_PAUSE_END(false, 1, null),
    CONVERT_CONSTANTS_START(false, 1, null),
    CONVERT_CONSTANTS_END(false, 1, null),
    PRE_REACT_CONTEXT_END(false, 1, null),
    UNPACKING_JS_BUNDLE_LOADER_CHECK_START(false, 1, null),
    UNPACKING_JS_BUNDLE_LOADER_CHECK_END(false, 1, null),
    UNPACKING_JS_BUNDLE_LOADER_EXTRACTED(false, 1, null),
    UNPACKING_JS_BUNDLE_LOADER_BLOCKED(false, 1, null),
    loadApplicationScript_startStringConvert(true),
    loadApplicationScript_endStringConvert(true),
    PRE_SETUP_REACT_CONTEXT_START(false, 1, null),
    PRE_SETUP_REACT_CONTEXT_END(false, 1, null),
    PRE_RUN_JS_BUNDLE_START(false, 1, null),
    ATTACH_MEASURED_ROOT_VIEWS_START(false, 1, null),
    ATTACH_MEASURED_ROOT_VIEWS_END(false, 1, null),
    CONTENT_APPEARED(false, 1, null),
    RELOAD(false, 1, null),
    DOWNLOAD_START(false, 1, null),
    DOWNLOAD_END(false, 1, null),
    REACT_CONTEXT_THREAD_START(false, 1, null),
    REACT_CONTEXT_THREAD_END(false, 1, null),
    GET_REACT_INSTANCE_MANAGER_START(false, 1, null),
    GET_REACT_INSTANCE_MANAGER_END(false, 1, null),
    GET_REACT_INSTANCE_HOLDER_SPEC_START(false, 1, null),
    GET_REACT_INSTANCE_HOLDER_SPEC_END(false, 1, null),
    BUILD_REACT_INSTANCE_MANAGER_START(false, 1, null),
    BUILD_REACT_INSTANCE_MANAGER_END(false, 1, null),
    PROCESS_INFRA_PACKAGE_START(false, 1, null),
    PROCESS_INFRA_PACKAGE_END(false, 1, null),
    PROCESS_PRODUCT_PACKAGE_START(false, 1, null),
    PROCESS_PRODUCT_PACKAGE_END(false, 1, null),
    CREATE_MC_MODULE_START(false, 1, null),
    CREATE_MC_MODULE_END(false, 1, null),
    CREATE_MC_MODULE_GET_METADATA_START(false, 1, null),
    CREATE_MC_MODULE_GET_METADATA_END(false, 1, null),
    REGISTER_JS_SEGMENT_START(true),
    REGISTER_JS_SEGMENT_STOP(true),
    VM_INIT(false, 1, null),
    ON_FRAGMENT_CREATE(false, 1, null),
    JAVASCRIPT_EXECUTOR_FACTORY_INJECT_START(false, 1, null),
    JAVASCRIPT_EXECUTOR_FACTORY_INJECT_END(false, 1, null),
    LOAD_REACT_NATIVE_SO_FILE_START(false, 1, null),
    LOAD_REACT_NATIVE_SO_FILE_END(false, 1, null),
    ROOT_VIEW_ON_MEASURE_START(false, 1, null),
    ROOT_VIEW_ON_MEASURE_END(false, 1, null),
    ROOT_VIEW_ATTACH_TO_REACT_INSTANCE_MANAGER_START(false, 1, null),
    ROOT_VIEW_ATTACH_TO_REACT_INSTANCE_MANAGER_END(false, 1, null),
    ROOT_VIEW_UPDATE_LAYOUT_SPECS_START(false, 1, null),
    ROOT_VIEW_UPDATE_LAYOUT_SPECS_END(false, 1, null),
    LOAD_REACT_NATIVE_FABRIC_SO_FILE_START(false, 1, null),
    LOAD_REACT_NATIVE_FABRIC_SO_FILE_END(false, 1, null),
    FABRIC_COMMIT_START(false, 1, null),
    FABRIC_COMMIT_END(false, 1, null),
    FABRIC_FINISH_TRANSACTION_START(false, 1, null),
    FABRIC_FINISH_TRANSACTION_END(false, 1, null),
    FABRIC_DIFF_START(false, 1, null),
    FABRIC_DIFF_END(false, 1, null),
    FABRIC_LAYOUT_START(false, 1, null),
    FABRIC_LAYOUT_END(false, 1, null),
    FABRIC_LAYOUT_AFFECTED_NODES(false, 1, null),
    FABRIC_BATCH_EXECUTION_START(false, 1, null),
    FABRIC_BATCH_EXECUTION_END(false, 1, null),
    FABRIC_UPDATE_UI_MAIN_THREAD_START(false, 1, null),
    FABRIC_UPDATE_UI_MAIN_THREAD_END(false, 1, null),
    REACT_BRIDGE_LOADING_START(false, 1, null),
    REACT_BRIDGE_LOADING_END(false, 1, null),
    REACT_BRIDGELESS_LOADING_START(false, 1, null),
    REACT_BRIDGELESS_LOADING_END(false, 1, null);

    private static final /* synthetic */ EnumEntries $ENTRIES = Gd.a.a(values());
    private final boolean hasMatchingNameMarker;

    ReactMarkerConstants(boolean z10) {
        this.hasMatchingNameMarker = z10;
    }

    /* synthetic */ ReactMarkerConstants(boolean z10, int i10, DefaultConstructorMarker defaultConstructorMarker) {
        this((i10 & 1) != 0 ? false : z10);
    }

    @NotNull
    public static EnumEntries getEntries() {
        return $ENTRIES;
    }

    /* JADX INFO: renamed from: hasMatchingNameMarker, reason: from getter */
    public final boolean getHasMatchingNameMarker() {
        return this.hasMatchingNameMarker;
    }
}
