package p458z8;

import android.os.Parcel;
import android.os.Parcelable;
import p170j8.AbstractC3851p;
import p404w8.p;

/* JADX INFO: loaded from: classes2.dex */
public final class c extends p {
    public static final Parcelable.Creator<c> CREATOR = new d();

    /* JADX INFO: renamed from: a, reason: collision with root package name */
    private final boolean f58488a;

    /* JADX INFO: renamed from: b, reason: collision with root package name */
    private final boolean f58489b;

    /* JADX INFO: renamed from: c, reason: collision with root package name */
    private final boolean f58490c;

    /* JADX INFO: renamed from: d, reason: collision with root package name */
    private final boolean f58491d;

    /* JADX INFO: renamed from: e, reason: collision with root package name */
    private final boolean f58492e;

    /* JADX INFO: renamed from: f, reason: collision with root package name */
    private final boolean f58493f;

    /* JADX INFO: renamed from: g, reason: collision with root package name */
    private final boolean f58494g;

    /* JADX INFO: renamed from: h, reason: collision with root package name */
    private final boolean f58495h;

    /* JADX INFO: renamed from: i, reason: collision with root package name */
    private final boolean f58496i;

    /* JADX INFO: renamed from: j, reason: collision with root package name */
    private final boolean f58497j;

    public c(boolean z10, boolean z11, boolean z12, boolean z13, boolean z14, boolean z15, boolean z16, boolean z17, boolean z18, boolean z19) {
        this.f58488a = z10;
        this.f58489b = z11;
        this.f58490c = z12;
        this.f58491d = z13;
        this.f58492e = z14;
        this.f58493f = z15;
        this.f58494g = z16;
        this.f58495h = z17;
        this.f58496i = z18;
        this.f58497j = z19;
    }

    public final boolean equals(Object obj) {
        if (!(obj instanceof c)) {
            return false;
        }
        if (this == obj) {
            return true;
        }
        c cVar = (c) obj;
        return this.f58488a == cVar.f58488a && this.f58489b == cVar.f58489b && this.f58490c == cVar.f58490c && this.f58491d == cVar.f58491d && this.f58492e == cVar.f58492e && this.f58493f == cVar.f58493f && this.f58494g == cVar.f58494g && this.f58495h == cVar.f58495h && this.f58496i == cVar.f58496i && this.f58497j == cVar.f58497j;
    }

    public final int hashCode() {
        return AbstractC3851p.b(Boolean.valueOf(this.f58488a), Boolean.valueOf(this.f58489b), Boolean.valueOf(this.f58490c), Boolean.valueOf(this.f58491d), Boolean.valueOf(this.f58492e), Boolean.valueOf(this.f58493f), Boolean.valueOf(this.f58494g), Boolean.valueOf(this.f58495h), Boolean.valueOf(this.f58496i), Boolean.valueOf(this.f58497j));
    }

    public final String toString() {
        return AbstractC3851p.c(this).a("forbiddenToHavePlayerProfile", Boolean.valueOf(this.f58488a)).a("requiresParentPermissionToShareData", Boolean.valueOf(this.f58489b)).a("hasSettingsControlledByParent", Boolean.valueOf(this.f58490c)).a("requiresParentPermissionToUsePlayTogether", Boolean.valueOf(this.f58491d)).a("canUseOnlyAutoGeneratedGamerTag", Boolean.valueOf(this.f58492e)).a("forbiddenToRecordVideo", Boolean.valueOf(this.f58493f)).a("shouldSeeEquallyWeightedButtonsInConsents", Boolean.valueOf(this.f58494g)).a("requiresParentConsentToUseAutoSignIn", Boolean.valueOf(this.f58495h)).a("shouldSeeSimplifiedConsentMessages", Boolean.valueOf(this.f58496i)).a("forbiddenToUseProfilelessRecall", Boolean.valueOf(this.f58497j)).toString();
    }

    @Override // android.os.Parcelable
    public final void writeToParcel(Parcel parcel, int i10) {
        boolean z10 = this.f58488a;
        int iA = p188k8.c.a(parcel);
        p188k8.c.c(parcel, 1, z10);
        p188k8.c.c(parcel, 2, this.f58489b);
        p188k8.c.c(parcel, 3, this.f58490c);
        p188k8.c.c(parcel, 4, this.f58491d);
        p188k8.c.c(parcel, 5, this.f58492e);
        p188k8.c.c(parcel, 6, this.f58493f);
        p188k8.c.c(parcel, 7, this.f58494g);
        p188k8.c.c(parcel, 8, this.f58495h);
        p188k8.c.c(parcel, 9, this.f58496i);
        p188k8.c.c(parcel, 10, this.f58497j);
        p188k8.c.b(parcel, iA);
    }
}
